name: PDF downloader
on:
  push:
    branches:
      - main
    paths:
      - "data/**"
jobs:
  Download-and-Transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: tool/fetch-PDF.sh data downloads

      - uses: actions/upload-artifact@v4
        with:
          name: PDF-Markdown
          path: downloads
