name: PDF downloader
on:
  push:
    branches:
      - main
    paths:
      - "data/**"
jobs:
  Download-and-Transform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install, Inject & Run
        run: |
          pnpm i
          cat > .env <<EOF
          ${{ secrets.ENV_FILE }}
          EOF
          find data/ -type f | grep -Ei .+\\.yml | xargs -I {} pnpm tool {}

      - uses: actions/upload-artifact@v4
        with:
          name: PDF-Markdown
          path: downloads
